window.ORIGEN_DATA = {
  creators: [
    {
      id: "pakarina",
      name: "Pakarina",
      type: "Colectivo artesanal",
      category: "Artesanía y tradición",
      location: "Yaruquí, Ecuador",
      country: "Ecuador",
      verified: false,
      profileStatus: "reference",
      referenceProfile: true,
      claimable: true,
      managedByRepresentative: false,
      referenceNote: "Perfil de referencia creado por ORIGEN a partir de material del piloto y referencias públicas. No está gestionado ni verificado por la entidad mencionada.",
      image: "assets/images/embroidery.jpg",
      cover: "assets/images/mural.jpg",
      short: "Referencia editorial del piloto sobre bordado y creación textil vinculados a Yaruquí.",
      story: "Este perfil es una referencia editorial del piloto ORIGEN. Su contenido deberá ser revisado, corregido o asumido por un representante autorizado antes de presentarse como perfil oficial.",
      tags: ["Bordado", "Textiles", "Memoria viva"],
      links: {},
      followers: 0,
      posts: []
    },
    {
      id: "chawar",
      name: "Chawar",
      type: "Emprendimiento cultural",
      category: "Gastronomía ancestral",
      location: "Pichincha, Ecuador",
      country: "Ecuador",
      verified: false,
      profileStatus: "reference",
      referenceProfile: true,
      claimable: true,
      managedByRepresentative: false,
      referenceNote: "Perfil de referencia creado por ORIGEN a partir de material del piloto y referencias públicas. No está gestionado ni verificado por la entidad mencionada.",
      image: "assets/images/chawar.jpg",
      cover: "assets/images/territory.jpg",
      short: "Referencia editorial del piloto sobre agave andino y prácticas tradicionales vinculadas al territorio.",
      story: "Este perfil es una referencia editorial del piloto ORIGEN. Su contenido deberá ser revisado, corregido o asumido por un representante autorizado antes de presentarse como perfil oficial.",
      tags: ["Agave andino", "Gastronomía", "Territorio"],
      links: {},
      followers: 0,
      posts: []
    },
    {
      id: "aji-de-piedra",
      name: "Ají de Piedra",
      type: "Negocio cultural",
      category: "Gastronomía tradicional",
      location: "Yaruquí, Ecuador",
      country: "Ecuador",
      verified: false,
      profileStatus: "reference",
      referenceProfile: true,
      claimable: true,
      managedByRepresentative: false,
      referenceNote: "Perfil de referencia creado por ORIGEN a partir de material del piloto y referencias públicas. No está gestionado ni verificado por la entidad mencionada.",
      image: "assets/images/gastronomy.jpg",
      cover: "assets/images/landscape.jpg",
      short: "Referencia editorial del piloto sobre gastronomía tradicional vinculada a Yaruquí.",
      story: "Este perfil es una referencia editorial del piloto ORIGEN. Su contenido deberá ser revisado, corregido o asumido por un representante autorizado antes de presentarse como perfil oficial.",
      tags: ["Cocina tradicional", "Recetas", "Hospitalidad"],
      links: {},
      followers: 0,
      posts: []
    },
    {
      id: "pushkana-runa",
      name: "Pushkana Runa",
      type: "Centro intercultural",
      category: "Cultura, bordado y danza",
      location: "Yaruquí, Ecuador",
      country: "Ecuador",
      verified: false,
      profileStatus: "reference",
      referenceProfile: true,
      claimable: true,
      managedByRepresentative: false,
      referenceNote: "Perfil de referencia creado por ORIGEN a partir de material del piloto y referencias públicas. No está gestionado ni verificado por la entidad mencionada.",
      image: "assets/images/dance.jpg",
      cover: "assets/images/mural.jpg",
      short: "Referencia editorial del piloto sobre actividades interculturales relacionadas con bordado, danza e investigación cultural.",
      story: "Este perfil es una referencia editorial del piloto ORIGEN. Su contenido deberá ser revisado, corregido o asumido por un representante autorizado antes de presentarse como perfil oficial.",
      tags: ["Interculturalidad", "Bordado", "Danza"],
      links: {},
      followers: 0,
      posts: []
    }
  ],
  categories: ["Todos", "Artesanía", "Gastronomía", "Territorio", "Música y danza", "Comunidad"],
  impact: [
    { value: "04", label: "Perfiles de referencia del piloto" },
    { value: "01", label: "País en validación inicial" },
    { value: "01", label: "Backend compartido web y futuras apps" },
    { value: "100%", label: "Perfiles sujetos a consentimiento y verificación" }
  ],
  posts: []
};
